apiVersion: v1
kind: PersistentVolume
metadata:
  name: homework-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: homework-storage-class
  hostPath:
    path: "/mnt/data/homework"
