apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  containers:
  - name: web-server
    image: nginx:latest 
    ports:
    - containerPort: 80
    volumeMounts:
    - name: homework-volume
      mountPath: /usr/share/nginx/html
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi" 
        cpu: "500m"    
    lifecycle:
      preStop:
        exec:
          command: ["rm", "-f", "/usr/share/nginx/html/index.html"]
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
  initContainers:
  - name: init-container
    image: busybox:1.28
    command: 
      - wget
      - "-O"
      - "/init/index.html"
      - http://info.cern.ch
    volumeMounts:
    - name: homework-volume
      mountPath: /init
  volumes:
  - name: homework-volume
    emptyDir: {}
